### ISSUE TITLE
Собрать torch c доступной cuda

### ISSUE THREAD

**Issue by skazankov** [skazankov/yolov5#2]
... попробовать поставить через conda

**Comment by andrewmitrofanov** [comment]
Я ставил торч через pip так как описано на официальном форумен nvidia: https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available/72048

**Comment by skazankov** [comment]
Для питона 3.6.9

```
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install python3-pip libopenblas-base libopenmpi-dev 
pip3 install Cython
pip3 install numpy
pip3 install --upgrade pip
pip3 install opencv-python
pip3 install opencv-contrib-python
wget https://nvidia.box.com/shared/static/p57jwntv436lfrd78inwl7iml6p13fzh.whl -O torch-1.8.0-cp36-cp36m-linux_aarch64.whl
pip3 install torch-1.8.0-cp36-cp36m-linux_aarch64.whl
pip3 install -r requirements.txt
```

**Comment by andrewmitrofanov** [comment]
sudo apt install redis-server

> Для питона 3.6.9
> 
> ```
> sudo apt-get update
> sudo apt-get dist-upgrade
> sudo apt-get install python3-pip libopenblas-base libopenmpi-dev 
> pip3 install Cython
> pip3 install numpy
> pip3 install --upgrade pip
> pip3 install opencv-python
> pip3 install opencv-contrib-python
> wget https://nvidia.box.com/shared/static/p57jwntv436lfrd78inwl7iml6p13fzh.whl -O torch-1.8.0-cp36-cp36m-linux_aarch64.whl
> pip3 install torch-1.8.0-cp36-cp36m-linux_aarch64.whl
> pip3 install -r requirements.txt
> ```
